export const zones=[
 {id:'root',name:'Rễ · Nội lực',icon:'🌱',hint:'Con người, kinh tế, khoa học và năng lực tự chủ'},
 {id:'trunk',name:'Thân · Chủ quyền',icon:'🎋',hint:'Nguyên tắc, lợi ích quốc gia và quyền tự quyết'},
 {id:'branch',name:'Cành · Hội nhập',icon:'🌏',hint:'Hợp tác quốc tế chủ động, linh hoạt và có chọn lọc'}
];

export const bambooRounds=[
 {title:'Mở cửa nhưng không đánh mất mình',context:'Sau bài học “bế quan tỏa cảng”, đất nước cần mở cửa để tiếp nhận tri thức mới nhưng vẫn phải giữ năng lực tự quyết.',lesson:'Độc lập tự chủ không đồng nghĩa với tự cô lập. Nội lực vững giúp đất nước tiếp thu thành tựu bên ngoài một cách có chọn lọc.',source:'Giáo trình Tư tưởng Hồ Chí Minh, NXB Chính trị quốc gia Sự thật, 2021, tr. 93.',cards:[['r1','Canh tân giáo dục và kỹ nghệ','root'],['r2','Đóng cửa với mọi tri thức bên ngoài',null],['r3','Giữ quyền quyết định các vấn đề quốc gia','trunk'],['r4','Nhượng lợi ích cốt lõi để đổi lấy viện trợ',null],['r5','Mở giao thương có chọn lọc','branch'],['r6','Phụ thuộc hoàn toàn vào một cường quốc',null]]},
 {title:'Giữ vững độc lập khi mở rộng quan hệ',context:'Việt Nam muốn mở rộng quan hệ với nhiều quốc gia để tranh thủ sức mạnh thời đại và giữ môi trường hòa bình.',lesson:'Giữ vững nguyên tắc độc lập, tự chủ; dựa vào sức mình và đa phương hóa quan hệ để tránh lệ thuộc.',source:'Hồ Chí Minh: Toàn tập; nội dung về kết hợp sức mạnh dân tộc với sức mạnh thời đại.',cards:[['s1','Củng cố khối đại đoàn kết dân tộc','root'],['s2','Chọn một nước và phụ thuộc hoàn toàn',null],['s3','Kiên định độc lập và lợi ích quốc gia','trunk'],['s4','Thỏa hiệp mọi nguyên tắc để có lợi ngắn hạn',null],['s5','Đa phương hóa, đa dạng hóa quan hệ','branch'],['s6','Từ chối mọi cơ chế hợp tác quốc tế',null]]},
 {title:'Gia nhập WTO và bài toán tự chủ kinh tế',context:'Hội nhập thương mại mở ra thị trường mới nhưng cũng tạo sức ép cạnh tranh và nguy cơ phụ thuộc vào một số thị trường, công nghệ.',lesson:'Hội nhập hiệu quả cần doanh nghiệp và chuỗi cung ứng trong nước đủ mạnh, đồng thời chủ động luật chơi và đa dạng hóa thị trường.',source:'Nội dung vận dụng về độc lập, tự chủ trong hội nhập kinh tế quốc tế.',cards:[['w1','Nâng năng lực doanh nghiệp trong nước','root'],['w2','Chỉ gia công, không phát triển công nghệ',null],['w3','Bảo vệ quyền hoạch định chính sách kinh tế','trunk'],['w4','Đánh đổi an ninh kinh tế lấy tăng trưởng',null],['w5','Đa dạng thị trường và đối tác','branch'],['w6','Đóng cửa, rút khỏi thương mại quốc tế',null]]},
 {title:'Ngoại giao Cây tre',context:'Trước biến động quốc tế, Việt Nam cần giữ vững mục tiêu chiến lược nhưng linh hoạt trong phương pháp và quan hệ đối tác.',lesson:'“Gốc vững, thân chắc, cành uyển chuyển” thể hiện bản lĩnh, nguyên tắc và khả năng ứng xử linh hoạt trước biến động.',source:'Nội dung bài học về “Dĩ bất biến, ứng vạn biến” và Ngoại giao Cây tre Việt Nam.',cards:[['d1','Xây dựng sức mạnh tổng hợp quốc gia','root'],['d2','Chạy theo mọi thay đổi từ bên ngoài',null],['d3','Giữ vững chủ quyền và lợi ích cốt lõi','trunk'],['d4','Cứng nhắc trong mọi tình huống',null],['d5','Linh hoạt phương pháp và đối tác','branch'],['d6','Trung lập bằng cách không quan hệ với ai',null]]},
 {title:'Bán dẫn, AI và năng lực làm chủ',context:'Việt Nam thu hút đầu tư công nghệ cao. Mục tiêu là tiếp nhận cơ hội quốc tế và từng bước làm chủ nhân lực, dữ liệu, công nghệ.',lesson:'Ngoại lực chỉ phát huy bền vững khi gắn với đào tạo con người, bảo vệ lợi ích quốc gia và hợp tác có điều kiện rõ ràng.',source:'Nội dung vận dụng về độc lập, tự chủ trong hội nhập công nghệ cao.',cards:[['a1','Đào tạo kỹ sư và năng lực nghiên cứu trong nước','root'],['a2','Thuê toàn bộ chuyên gia, bỏ qua đào tạo nội địa',null],['a3','Bảo vệ dữ liệu và an ninh công nghệ quốc gia','trunk'],['a4','Hạ mọi tiêu chuẩn an ninh để thu hút vốn',null],['a5','Hợp tác chuyển giao công nghệ có chọn lọc','branch'],['a6','Cấm mọi doanh nghiệp công nghệ nước ngoài',null]]}
].map(round=>({...round,cards:round.cards.map(([id,title,zone])=>({id,title,zone}))}));

export function scoreSelection(selection,round){
 const correct=Object.entries(selection).filter(([zone,id])=>round.cards.find(card=>card.id===id)?.zone===zone).length;
 return {correct,points:correct*30+(correct===3?10:0)};
}
