import React,{useEffect,useState}from'react';import{createRoot}from'react-dom/client';
import content from'./content.json';import{questions}from'./questions';import BambooGame from'./BambooGame';import'./style.css';import'./refresh.css';
const tabs=['Thử thách 10 câu','Cân bằng Cây tre','Lý luận cốt lõi','Tư liệu lịch sử','Bảng xếp hạng','Phụ lục AI'],letters=['A','B','C','D'];
const load=(key,fallback)=>{try{return{...fallback,...JSON.parse(localStorage.getItem(key)||'{}')}}catch{return fallback}};
const quizBlank={n:0,pick:null,done:false,score:0,history:[],complete:false};
function Appendix(){return <section className="reading"><div className="section-heading"><div><span className="eyebrow">MINH BẠCH QUÁ TRÌNH</span><h2>Phụ lục: AI được dùng như thế nào?</h2></div></div><div className="ai-grid"><article className="panel ai-card"><b>01</b><h3>AI hỗ trợ sản xuất</h3><p>Hỗ trợ thiết kế giao diện React, viết mã, sửa lỗi, chấm điểm và chuẩn hóa cách trình bày câu hỏi.</p></article><article className="panel ai-card"><b>02</b><h3>Con người kiểm duyệt</h3><p>AI không được dùng làm nguồn học thuật. Nhóm chịu trách nhiệm kiểm tra đáp án và nội dung cuối.</p></article><article className="panel ai-card"><b>03</b><h3>Nguồn kiến thức</h3><p>Giáo trình Tư tưởng Hồ Chí Minh (2021), Hồ Chí Minh: Toàn tập (2011) và văn kiện chính thức.</p></article><article className="panel ai-card"><b>04</b><h3>Quy trình xác minh</h3><p>Nguồn gốc → AI hỗ trợ → Nhóm đối chiếu → Sản phẩm. Số trang cần khớp bản sách lớp đang dùng.</p></article></div></section>}
function App(){
 const[tab,setTab]=useState(0),[quiz,setQuiz]=useState(()=>load('hcm202-journey',quizBlank)),[bambooScore,setBambooScore]=useState(()=>Number(localStorage.getItem('hcm202-bamboo-score')||0)),[journeyDone,setJourneyDone]=useState(()=>localStorage.getItem('hcm202-journey-done')==='1'),[name,setName]=useState(''),[board,setBoard]=useState(()=>{try{return JSON.parse(localStorage.getItem('hcm202-board-1500')||'[]')}catch{return[]}}),[present,setPresent]=useState(false);
 const q=questions[quiz.n],ok=quiz.pick===q.answer,progress=Math.round((quiz.n+(quiz.done?1:0))*10),total=quiz.score+bambooScore;
 useEffect(()=>localStorage.setItem('hcm202-journey',JSON.stringify(quiz)),[quiz]);
 function resetAll(target=0){localStorage.removeItem('hcm202-journey');localStorage.removeItem('hcm202-bamboo-progress');localStorage.removeItem('hcm202-bamboo-score');localStorage.removeItem('hcm202-journey-done');setQuiz(quizBlank);setBambooScore(0);setJourneyDone(false);setName('');setTab(target)}
 function submit(){if(quiz.pick===null||quiz.done)return;setQuiz(s=>({...s,done:true,score:s.score+(s.pick===q.answer?100:0),history:[...s.history,s.pick===q.answer]}))}
 function next(){if(quiz.n===9)setQuiz(s=>({...s,complete:true}));else setQuiz(s=>({...s,n:s.n+1,pick:null,done:false}))}
 function finishBamboo(score){setBambooScore(score);setJourneyDone(true);localStorage.setItem('hcm202-bamboo-score',score);localStorage.setItem('hcm202-journey-done','1')}
 function save(){if(!journeyDone)return;const entry={name:name.trim()||'Nhóm thuyết trình',quiz:quiz.score,bamboo:bambooScore,score:total,date:new Date().toLocaleDateString('vi-VN')};const next=[...board,entry].sort((a,b)=>b.score-a.score).slice(0,20);localStorage.setItem('hcm202-board-1500',JSON.stringify(next));setBoard(next);setTab(4);setName('')}
 async function full(){setPresent(!present);try{document.fullscreenElement?await document.exitFullscreen():await document.documentElement.requestFullscreen()}catch{}}
 return <div className={present?'app presentation':'app'}><header><a className="brand" href="#" onClick={e=>{e.preventDefault();setTab(0)}}><span className="brand-icon">★</span><span>HCM202<small>TƯ TƯỞNG HỒ CHÍ MINH</small></span></a><button onClick={full}>⛶ {present?'Thu gọn':'Thuyết trình'}</button></header><main><section className="hero"><div><div className="eyebrow">ĐỘC LẬP DÂN TỘC GẮN LIỀN VỚI CHỦ NGHĨA XÃ HỘI</div><h1>Rễ vững vàng.<br/><em>Vươn ra thế giới.</em></h1><p>Hành trình 1.500 điểm: hiểu đúng lý luận và vận dụng qua những quyết sách hội nhập.</p></div><div className="hero-seal"><span>★</span><small>HÀNH TRÌNH</small><strong>15 THỬ THÁCH<br/>HCM202</strong><i>Hiểu đúng · Vận dụng tốt</i></div></section><nav>{tabs.map((x,i)=><button className={tab===i?'active':''} onClick={()=>setTab(i)} key={x}><span>0{i+1}</span>{x}{i===1&&!quiz.complete&&<i className="nav-lock">🔒</i>}</button>)}</nav>
 {tab===0?<><div className="section-heading"><div><span className="eyebrow">VÒNG 1 · THỬ THÁCH KIẾN THỨC</span><h2>Hành trình độc lập và hội nhập</h2></div><div className="score"><small>ĐIỂM QUIZ</small><strong>{quiz.score}<span> / 1.000</span></strong></div></div><section className="how-to"><div className="how-title"><span>CÁCH CHƠI</span><strong>3 bước · 10 câu</strong></div><ol><li><b>1</b><span><strong>Đọc câu hỏi</strong><small>Nắm từ khóa chính.</small></span></li><li><b>2</b><span><strong>Chọn A–D</strong><small>Một đáp án đúng.</small></span></li><li><b>3</b><span><strong>Xem bài học</strong><small>Đúng nhận 100 điểm.</small></span></li></ol></section><section className="quiz-shell"><aside className="panel quiz-status"><div className="round-number">{String(quiz.n+1).padStart(2,'0')}</div><span className="eyebrow">CÂU HỎI / 10</span><div className="ring" style={{'--progress':progress*3.6+'deg'}}><strong>{progress}%</strong><small>HOÀN THÀNH</small></div><div className="mini-stats"><div><strong>{quiz.history.filter(Boolean).length}</strong><small>ĐÚNG</small></div><div><strong>{quiz.history.filter(x=>!x).length}</strong><small>SAI</small></div></div><button className="text-button" onClick={()=>resetAll(0)}>↺ Chơi lại hành trình</button></aside><article className="panel question-card"><div className="question-meta"><span>{q.topic}</span><b>100 ĐIỂM</b></div><h2>{q.question}</h2><div className="answer-grid">{q.options.map((x,i)=><button key={x} disabled={quiz.done||quiz.complete} onClick={()=>setQuiz(s=>({...s,pick:i}))} className={`answer-option ${quiz.pick===i?'selected':''} ${quiz.done&&i===q.answer?'correct':''} ${quiz.done&&quiz.pick===i&&i!==q.answer?'wrong':''}`}><b>{letters[i]}</b><span>{x}</span>{quiz.done&&i===q.answer&&<i>✓</i>}{quiz.done&&quiz.pick===i&&i!==q.answer&&<i>×</i>}</button>)}</div>{quiz.complete?<div className="unlock-card"><span>🎋</span><h3>Đã mở khóa vòng Cân bằng Cây tre</h3><p>Điểm quiz của bạn: <b>{quiz.score}/1.000</b>. Tiếp tục năm tình huống để hoàn thành hành trình 1.500 điểm.</p><button className="primary" onClick={()=>setTab(1)}>Tiếp tục vòng Cân bằng Cây tre →</button></div>:!quiz.done?<><button className="primary submit-answer" disabled={quiz.pick===null} onClick={submit}>Chốt đáp án <span>→</span></button><small className="hint">Có thể đổi lựa chọn trước khi chốt.</small></>:<div className={'inline-result '+(ok?'is-correct':'is-wrong')}><div><span>{ok?'CHÍNH XÁC':'CHƯA CHÍNH XÁC'}</span><strong>{ok?'+100 điểm':'Đáp án đúng: '+letters[q.answer]}</strong></div><p>{q.lesson}</p><small>📖 {q.source}</small><button className="primary" onClick={next}>{quiz.n===9?'Mở khóa vòng Cây tre':'Câu tiếp theo'} <span>→</span></button></div>}</article></section><div className="question-dots">{questions.map((_,i)=><span key={i} className={`${i===quiz.n?'current':''} ${i<quiz.history.length?(quiz.history[i]?'right':'miss'):''}`}>{i+1}</span>)}</div></>:
 tab===1?<BambooGame unlocked={quiz.complete} quizScore={quiz.score} onComplete={finishBamboo} onReset={()=>resetAll(0)}/>:tab===5?<Appendix/>:tab===4?<section className="panel board"><div className="section-heading"><div><span className="eyebrow">THÀNH TÍCH CỦA LỚP</span><h2>Bảng xếp hạng hành trình</h2></div><span className="pill">Tối đa 1.500 điểm</span></div>{board.length?<div className="table-wrap"><table><thead><tr><th>Hạng</th><th>Nhóm</th><th>Quiz</th><th>Cây tre</th><th>Tổng</th><th>Ngày</th></tr></thead><tbody>{board.map((b,i)=><tr key={i}><td><span className="rank">{String(i+1).padStart(2,'0')}</span></td><td>{b.name}</td><td>{b.quiz}/1.000</td><td>{b.bamboo}/500</td><td className="gold">{b.score}/1.500</td><td>{b.date}</td></tr>)}</tbody></table></div>:<div className="empty"><h3>Chưa có hành trình hoàn chỉnh</h3><p>Hoàn thành quiz và Cân bằng Cây tre để ghi tên vào bảng.</p></div>}</section>:<section className="reading"><div className="section-heading"><div><span className="eyebrow">NỘI DUNG THUYẾT TRÌNH</span><h2>{tabs[tab]}</h2></div></div><div className="original-content" dangerouslySetInnerHTML={{__html:tab===2?content.theory:content.cases}}/></section>}
 <footer><span>HCM202 · Độc lập trong tư duy, chủ động trong hội nhập.</span><span>10 câu + 5 tình huống · 1.500 điểm</span></footer></main>{journeyDone&&tab===1&&<div className="overlay"><section className="result final-result"><span className="final-icon">★</span><div className="eyebrow">HOÀN THÀNH TOÀN BỘ HÀNH TRÌNH</div><h2>{total>=1200?'Bản lĩnh hội nhập vững vàng!':total>=800?'Bạn đã nắm được nền tảng':'Cùng ôn lại bài học nhé!'}</h2><div className="result-score">{total}<small>/ 1.500 · Quiz {quiz.score} + Cây tre {bambooScore}</small></div><label className="name-label">Tên nhóm / người chơi</label><input value={name} maxLength="40" onChange={e=>setName(e.target.value)} placeholder="Ví dụ: Nhóm 7 – HCM202"/><button className="primary" onClick={save}>Lưu vào bảng xếp hạng <span>→</span></button><button className="text-button" onClick={()=>resetAll(0)}>Chơi lại toàn bộ</button></section></div>}</div>
}
createRoot(document.getElementById('root')).render(<App/>);
